docs_dir: blitzy-docs
site_name: 'blitzy-vllm'
nav:
  - Home: index.md
  - Project Guide: project-guide.md
  - Technical Specifications: technical-specifications.md
plugins:
  - techdocs-core
  - mermaid2